#
# Makefile for building the shared software libraries (swlibs) for x86-64 Linux
#

# ---
# Compiler and flags
# ---
CC = gcc
AR = ar
# Add top-level include path so headers like 3dfx.h can be found
CFLAGS = -m64 -msse2 -O2 -fPIC -Wall -I../incsrc -I./fxmisc -I./newpci/pcilib

# ---
# Source files
# ---

# Include all miscellaneous utility files
C_SRCS_FXMISC = $(wildcard fxmisc/*.c)
OBJS_FXMISC = $(patsubst %.c, %.o, $(C_SRCS_FXMISC))

# Specifically list the PCI lib files that are compatible with Linux
C_SRCS_PCILIB = \
	newpci/pcilib/fxpci.c \
	newpci/pcilib/fxinfo.c \
	newpci/pcilib/fxlinux.c \
	newpci/pcilib/fxmsr.c \
	newpci/pcilib/sst1_pci.c

OBJS_PCILIB = $(patsubst %.c, %.o, $(C_SRCS_PCILIB))

# ---
# Rules
# ---
all: libswlibs.a

libswlibs.a: $(OBJS_FXMISC) $(OBJS_PCILIB)
	$(AR) rcs $@ $^

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

clean:
	rm -f *.a
	find . -name "*.o" -exec rm {} \;

.PHONY: all clean