#
# Copyright (c) 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010
#   The H3DK project.  All rights reserved.
#
# ... (copyright header) ...
#
# Makefile for building glide3x library for linux
#

# ---
# User definable variables
# ---

# Default is to build for pentium-pro (optimised for pentium-2/3)
# To build for a different architecture, uncomment one of the CPU definitions below
# CPU = pentium
# CPU = k6
# CPU = athlon
CPU = x86-64

# Default is to build with debugging information
# To build without debugging information, uncomment the following line
# DEBUG = 0

# Default is to build for X11
# To build for SVGAlib, uncomment the following line
# GRX = svga

# ---
# Compiler and flags
# ---

CC = gcc
AS = as
LD = ld
AR = ar

# ---
# Architecture specific flags
# ---

ifeq ($(CPU), x86-64)
  CFLAGS_CPU = -m64 -msse2 -O2 -fPIC
  ASFLAGS_CPU = -m64
  LDFLAGS_CPU = -m64
else
  # ... (other CPU architectures) ...
endif

# ---
# Debugging flags
# ---

ifeq ($(DEBUG), 0)
  CFLAGS_DEBUG = -DNDEBUG
else
  CFLAGS_DEBUG = -g -DDEBUG
endif

# ---
# GRX specific flags
# ---

ifeq ($(GRX), svga)
  # ... (svga flags) ...
else
  CFLAGS_GRX = -I/usr/X11R6/include
  LDFLAGS_GRX = -L/usr/X11R6/lib -lX11 -lXxf86vm
endif

# ---
# General flags
# ---

CFLAGS = $(CFLAGS_CPU) $(CFLAGS_DEBUG) $(CFLAGS_GRX) -I../incsrc -I../../incsrc -I../../../swlibs/fxmisc -I../../../swlibs/newpci/pcilib -Wall
ASFLAGS = $(ASFLAGS_CPU)
LDFLAGS = $(LDFLAGS_CPU) $(LDFLAGS_GRX)

# ---
# Source files
# ---

C_SRCS = \
	$(wildcard *.c) \
	$(wildcard ../cinit/*.c) \
	$(wildcard ../glide3/*.c) \
	$(wildcard ../minihwc/*.c) \
	$(wildcard ../../swlibs/fxmisc/*.c) \
	$(wildcard ../../swlibs/newpci/pcilib/*.c)

ASM_SRCS = \
	$(wildcard ../glide3/*.S)

OBJS = \
	$(patsubst %.c, %.o, $(C_SRCS)) \
	$(patsubst %.S, %.o, $(ASM_SRCS))

# ---
# Rules
# ---

all: libglide3x.so

libglide3x.so: $(OBJS)
	$(CC) -shared -o $@ $(LDFLAGS) $^

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

%.o: %.S
	$(CC) $(CFLAGS) $(ASFLAGS) -c $< -o $@

clean:
	rm -f *.o libglide3x.so
	find . -name "*.o" -exec rm {} \;

.PHONY: all clean