#
# Makefile for building Glide for H3 with linux-gcc
#

#
# Standard definitions
#
include ../../../../swlibs/include/make/3dfx.linux.mak

#
# Local definitions
#
DEFS = -DGLIDE_STRIP_TRIANGLE -DGLIDE_PACKET3_TRI_STRIP -DH3 -DGLIDE_MULTIPLATFORM -D__GCC__ -D__linux__ -DP6FENCE -DGLIDE_SO -DGLIDE_NUM_TMU=2
INCLUDES = -I. -I../../../incsrc -I../../../../swlibs/fxmisc -I../../../../swlibs/newpci/pcilib -I../../minihwc -I../../cinit

#
# Main C files
#
C_SOURCES = gglide.c gerror.c gdraw.c gaa.c g3df.c ditex.c distate.c glfb.c gsplash.c gsst.c gstrip.c gtex.c gtexdl.c gu.c guclip.c gump.c gutex.c gxdraw.c fifo.c fxgasm.c gbanner.c gpci.c

#
# Derive object file names
#
OBJECTS = $(C_SOURCES:.c=.o)

#
# Main rule
#
all: libglide2x.so

#
# Library rule
#
libglide2x.so: $(OBJECTS)
	$(CC) $(LDFLAGS) -o $@ $(OBJECTS) -L../../../../swlibs -lswlibs

#
# Cleanup rules
#
clean:
	-rm -f $(OBJECTS)

realclean: clean
	-rm -f libglide2x.so