#
# Makefile for building glide3x library for linux
#

# ---
# User definable variables
# ---
CPU = x86-64
DEBUG = 0
# GRX = svga

# ---
# Compiler and flags
# ---
CC = gcc
AS = as
LD = ld
AR = ar

# ---
# Architecture specific flags
# ---
ifeq ($(CPU), x86-64)
  CFLAGS_CPU = -m64 -msse2 -O2 -fPIC -mpc64
  ASFLAGS_CPU = -m64
  LDFLAGS_CPU = -m64
else
  # Fallback for other architectures if needed
  CFLAGS_CPU = -O2 -fPIC
  ASFLAGS_CPU =
  LDFLAGS_CPU =
endif

# ---
# Debugging flags
# ---
ifeq ($(DEBUG), 0)
  CFLAGS_DEBUG = -DNDEBUG
else
  CFLAGS_DEBUG = -g -DDEBUG
endif

# ---
# GRX specific flags
# ---
ifeq ($(GRX), svga)
  CFLAGS_GRX = -I../../../swlibs/svga
  LDFLAGS_GRX = -L../../../swlibs/svga -lvgagl
else
  CFLAGS_GRX = -I/usr/X11R6/include
  LDFLAGS_GRX = -L/usr/X11R6/lib -lX11 -lXxf86vm
endif

# ---
# General flags
# ---
CFLAGS = $(CFLAGS_CPU) $(CFLAGS_DEBUG) $(CFLAGS_GRX) -I../../incsrc -I../../../incsrc -I../../../../swlibs/fxmisc -I../../../../swlibs/newci/pcilib -Wall
ASFLAGS = $(ASFLAGS_CPU)
LDFLAGS = $(LDFLAGS_CPU) $(LDFLAGS_GRX)

# ---
# Source files
# ---
C_SRCS = \
	$(wildcard *.c) \
	$(wildcard ../../cinit/*.c) \
	$(wildcard ../../../minihwc/*.c) \
	$(wildcard ../../../../swlibs/fxmisc/*.c) \
	$(wildcard ../../../../swlibs/newpci/pcilib/*.c)

ASM_SRCS = \
	$(wildcard *.S)

OBJS = \
	$(patsubst %.c, %.o, $(C_SRCS)) \
	$(patsubst %.S, %.o, $(ASM_SRCS))

# ---
# Rules
# ---
all: libglide3x.so

libglide3x.so: $(OBJS)
	$(CC) -shared -o $@ $(LDFLAGS) $^

%.o: %.c
	$(CC) $(CFLAGS) -c $< -o $@

%.o: %.S
	$(CC) $(CFLAGS) $(ASFLAGS) -c $< -o $@

clean:
	rm -f *.o libglide3x.so
	find . -name "*.o" -exec rm {} \;

.PHONY: all clean